restaurant/menu/urls.py
from django.urls import path
from menu.views import DescriptionListView, IndexView

app_name = 'menu'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('menu/', DescriptionListView.as_view(), name='menu')
]

restaurant/restaurant/urls.py
from django.contrib import admin
from django.urls import path, include
from menu.views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('menu/', include('menu.urls', namespace='menu'))
]

restaurant/menu/models.py
from django.db import models


class DishModel(models.Model):
    name = models.CharField(max_length=64)

    def __str__(self):
        return self.name


class DescriptionModel(models.Model):
    description = models.CharField(max_length=256)
    link = models.URLField(max_length=200, blank=True)
    dish = models.ForeignKey(to=DishModel, on_delete=models.CASCADE)

restaurant/menu/views.py
from django.shortcuts import render
from django.views.generic import ListView, TemplateView

from menu.models import DescriptionModel


# Create your views here.

class IndexView(TemplateView):
    template_name = 'menu/index.html'


class DescriptionListView(ListView):
    model = DescriptionModel
    template_name = 'menu/menu.html'
    title = "Меню"

restaurant/menu/templates/menu/base.html
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <header>
        <nav>
            <ul>
                <li><a href="admin/">Ресторан</a></li>
                <li>
                    <ul>
                        <li><a href="{% url 'index' %}">Ресторане</a></li>
                        <li><a href="{% url 'menu:menu' %}">Меню</a></li>
                    </ul>
                </li>
            </ul>
        </nav>
    </header>
    <main>
        {% block content %}{% endblock %}
    </main>
</body>
</html>

restaurant/menu/templates/menu/index.html
{% extends "menu/base.html" %}

{% block title %}О компании{% endblock %}

{% block content %}
    <h1>О ресторане</h1>
    <p>Одним из лучших ресторанов Москвы является ресторан "Турандот", как они сами пишут о себе, "ресторан паназиатской кухни с дворцовым интерьером на Тверском бульваре". Вход с Тверского бульвара к ним неприметный, а вот внутри интерьер действительно роскошный.</p>
{% endblock %}

restaurant/menu/templates/menu/menu.html
{% extends "menu/base.html" %}

{% block title %}Контакты{% endblock %}

{% block content %}
<head>
    <title>Restaurant Menu</title>
    <style>
        .menu-item {
            cursor: pointer;
        }
        .menu-description {
            display: none;
        }
    </style>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script>
        $(document).ready(function(){
            $('.menu-item').click(function(){
                $(this).next('.menu-description').slideToggle();
            });
        });
    </script>
</head>
<body>
    <a href="/admin/"><h1>Restaurant Menu</h1></a>
{% for dishs in object_list %}
    <div class="menu-item"><h2>{{ dishs.dish }}</h2></div>
    <div class="menu-description">
        <p>{{ dishs.description }}</p><a href="{{ dishs.link }}">Подробнее тут!</a>
    </div>
{% endfor %}
</body>
{% endblock %}